import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideNav from "@/components/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} bg-[#DFE3ED] h-full antialiased`}
    >
      <body className="flex min-h-screen">

        {/* Sidebar (hidden on small screens) */}
        <div className="hidden md:block">
          <SideNav />
        </div>

        {/* Main Content */}
        <div className="flex flex-col flex-1">

          {/* Navbar */}
          <div className="w-full max-w-[1200px] mx-auto px-4 sm:px-6 md:px-8 py-4">
            <Navbar />
          </div>

          {/* Page Content */}
          <main className="w-full max-w-[1200px] mx-auto px-4 sm:px-6 md:px-8 py-4">
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}