import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideNav from "@/components/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} bg-[#DFE3ED] ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex   min-h-full">
        <SideNav />
        <div className=" w-full flex flex-col items-center">
          <div className="w-[1040px]">
            <Navbar />

            <div className="w-1/6">
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
